#!/bin/sh
# grim installer — bootstrap (served from the Grimoire docs site)
#
# Fetches and runs the latest cargo-dist installer for grim from GitHub
# Releases. The real installer is generated by cargo-dist and verifies the
# downloaded archive's SHA-256 before installing; this stable URL is just a
# front door so the install command does not have to name a version.
#
#   curl --proto '=https' --tlsv1.2 -LsSf https://grimoire.rs/install.sh | sh
#
# Honors the same environment as the cargo-dist installer, e.g.
# GRIMOIRE_INSTALL_DIR to choose the install location. Any arguments to this
# script are forwarded to the cargo-dist installer (e.g. --no-modify-path).
set -eu

INSTALLER_URL="https://github.com/grimoire-rs/grimoire/releases/latest/download/grimoire-installer.sh"

tmp="$(mktemp)" || {
    echo "grim install: cannot create a temporary file" >&2
    exit 1
}
# Expand $tmp now (not at trap time) so cleanup always targets this file.
# shellcheck disable=SC2064
trap "rm -f \"$tmp\"" EXIT INT TERM

if command -v curl >/dev/null 2>&1; then
    curl --proto '=https' --tlsv1.2 -LsSf "$INSTALLER_URL" -o "$tmp"
elif command -v wget >/dev/null 2>&1; then
    wget --https-only -qO "$tmp" "$INSTALLER_URL"
else
    echo "grim install: need curl or wget on PATH" >&2
    exit 1
fi

sh "$tmp" "$@"
