# grim installer — bootstrap (served from the Grimoire docs site)
#
# Fetches and runs the latest cargo-dist PowerShell installer for grim from
# GitHub Releases. The real installer is generated by cargo-dist and verifies
# the downloaded archive's SHA-256 before installing; this stable URL is just
# a front door so the install command does not have to name a version.
#
#   irm https://michael-herwig.github.io/grimoire/install.ps1 | iex
#
$ErrorActionPreference = 'Stop'
$installer = 'https://github.com/michael-herwig/grimoire/releases/latest/download/grimoire-installer.ps1'
Invoke-Expression (Invoke-RestMethod -Uri $installer)
