// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Grimoire Authors

//! The client-transform seam: turn a materialized canonical artifact tree
//! into the on-disk layout one client expects.
//!
//! Claude and OpenCode read the canonical files verbatim (only the
//! directory differs). Copilot reads skills verbatim but **transforms** a
//! rule into a `<name>.instructions.md` file: the `paths:` frontmatter is
//! stripped and a provenance header is prepended. The transform is
//! deterministic — regenerating the same rule at the same pinned
//! identifier yields byte-identical output, so a user edit to a generated
//! file is detected as drift exactly like a canonical file (the installer
//! hashes the *expected* generated bytes, not the input).

use std::path::{Path, PathBuf};

use crate::oci::ArtifactKind;
use crate::skill::RuleFrontmatter;

use super::install_error::{InstallError, InstallErrorKind};

/// A supported client target.
///
/// Closed internal enum (the binary is the only consumer); `Default` is
/// [`ClientTarget::Claude`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ClientTarget {
    /// Claude Code — `.claude/{skills,rules}`.
    #[default]
    Claude,
    /// OpenCode — `.opencode/{skills,rules}`.
    OpenCode,
    /// GitHub Copilot — `.github/{skills,instructions}` (rules transformed).
    Copilot,
}

impl std::str::FromStr for ClientTarget {
    type Err = InstallError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "claude" => Ok(Self::Claude),
            "opencode" => Ok(Self::OpenCode),
            "copilot" => Ok(Self::Copilot),
            other => Err(InstallError::without_reference(InstallErrorKind::UnsupportedClient(
                other.to_string(),
            ))),
        }
    }
}

impl std::fmt::Display for ClientTarget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Claude => "claude",
            Self::OpenCode => "opencode",
            Self::Copilot => "copilot",
        })
    }
}

/// One file produced for an client target.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MaterializedFile {
    /// The absolute on-disk path written.
    pub path: PathBuf,
    /// Whether the file is a generated transform (vs. a canonical copy).
    /// Generated files are integrity-hashed against their *expected*
    /// bytes so a user edit is still detected as drift.
    pub generated: bool,
}

impl ClientTarget {
    /// The client root directory name under the workspace (`.claude`,
    /// `.opencode`, `.github`).
    fn root_dir(self) -> &'static str {
        match self {
            Self::Claude => ".claude",
            Self::OpenCode => ".opencode",
            Self::Copilot => ".github",
        }
    }

    /// The absolute install path for the named artifact of `kind` under
    /// `workspace`. A skill installs as a directory; a rule as a single
    /// file (whose name/extension may differ per client).
    pub fn path_for(self, workspace: &Path, kind: ArtifactKind, name: &str) -> PathBuf {
        let root = workspace.join(self.root_dir());
        match (self, kind) {
            (_, ArtifactKind::Skill) => root.join("skills").join(name),
            (Self::Claude | Self::OpenCode, ArtifactKind::Rule) => root.join("rules").join(format!("{name}.md")),
            (Self::Copilot, ArtifactKind::Rule) => root.join("instructions").join(format!("{name}.instructions.md")),
            // Bundles never materialize; they expand into members.
            (_, ArtifactKind::Bundle) => unreachable!("bundles are never materialized; they expand into members"),
        }
    }

    /// Materialize the canonical artifact tree at `artifact_root` into the
    /// client layout at `dest`.
    ///
    /// `artifact_root` is the extracted canonical content: the skill
    /// directory (`<name>/…`) or the rule file (`<name>.md`). `dest` is
    /// the final path from [`Self::path_for`]. For a skill, the tree is
    /// copied verbatim. For a rule, Claude/OpenCode copy verbatim;
    /// Copilot transforms (strip `paths:`, prepend provenance header).
    ///
    /// # Errors
    ///
    /// [`InstallErrorKind::TargetIo`] for a filesystem failure;
    /// [`InstallErrorKind::MaterializeFailed`] for an unreadable rule.
    pub fn materialize(
        self,
        kind: ArtifactKind,
        name: &str,
        artifact_root: &Path,
        dest: &Path,
        pinned: &str,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        match kind {
            ArtifactKind::Skill => self.materialize_skill(artifact_root, dest),
            ArtifactKind::Rule => self.materialize_rule(name, artifact_root, dest, pinned),
            // Bundles never materialize; they expand into members.
            ArtifactKind::Bundle => unreachable!("bundles are never materialized; they expand into members"),
        }
    }

    /// Copy a skill tree verbatim into `dest` (all clients).
    fn materialize_skill(self, artifact_root: &Path, dest: &Path) -> Result<Vec<MaterializedFile>, InstallError> {
        let mut out = Vec::new();
        copy_tree(artifact_root, dest, &mut out)?;
        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }

    /// Materialize a rule: a verbatim copy for Claude/OpenCode, the
    /// transformed `*.instructions.md` for Copilot.
    fn materialize_rule(
        self,
        _name: &str,
        artifact_root: &Path,
        dest: &Path,
        pinned: &str,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let bytes = std::fs::read(artifact_root).map_err(|e| target_io(artifact_root, e))?;
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }

        match self {
            Self::Claude | Self::OpenCode => {
                std::fs::write(dest, &bytes).map_err(|e| target_io(dest, e))?;
                Ok(vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: false,
                }])
            }
            Self::Copilot => {
                let doc = String::from_utf8_lossy(&bytes);
                let transformed = copilot_instructions(&doc, pinned, artifact_root)?;
                std::fs::write(dest, transformed.as_bytes()).map_err(|e| target_io(dest, e))?;
                Ok(vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: true,
                }])
            }
        }
    }
}

/// Render the exact bytes the Copilot rule transform produces for `doc`
/// pinned at `pinned`. Deterministic: same input ⇒ byte-identical output,
/// so the installer can hash this as the integrity anchor for a generated
/// file (a user edit then diverges from it = detected drift).
pub fn copilot_instructions(doc: &str, pinned: &str, src: &Path) -> Result<String, InstallError> {
    let parsed = RuleFrontmatter::parse_doc(doc, src)
        .map_err(|e| InstallError::without_reference(InstallErrorKind::MaterializeFailed(e.to_string())))?;
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- generated by grim from {pinned}; edits will be overwritten -->\n"
    ));
    out.push_str(&parsed.body);
    Ok(out)
}

/// Recursively copy every regular file under `src` into `dst`, preserving
/// the relative structure. Records each written file as a canonical
/// (non-generated) [`MaterializedFile`].
fn copy_tree(src: &Path, dst: &Path, out: &mut Vec<MaterializedFile>) -> Result<(), InstallError> {
    let meta = std::fs::symlink_metadata(src).map_err(|e| target_io(src, e))?;
    if meta.is_dir() {
        std::fs::create_dir_all(dst).map_err(|e| target_io(dst, e))?;
        let mut children: Vec<PathBuf> = std::fs::read_dir(src)
            .map_err(|e| target_io(src, e))?
            .map(|e| e.map(|e| e.path()))
            .collect::<std::io::Result<Vec<_>>>()
            .map_err(|e| target_io(src, e))?;
        children.sort();
        for child in children {
            let name = child.file_name().unwrap_or_default();
            copy_tree(&child, &dst.join(name), out)?;
        }
    } else if meta.is_file() {
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }
        std::fs::copy(src, dst).map_err(|e| target_io(dst, e))?;
        out.push(MaterializedFile {
            path: dst.to_path_buf(),
            generated: false,
        });
    }
    Ok(())
}

fn target_io(path: &Path, source: std::io::Error) -> InstallError {
    InstallError::without_reference(InstallErrorKind::TargetIo {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn from_str_and_display_round_trip_lowercase() {
        for (s, t) in [
            ("claude", ClientTarget::Claude),
            ("opencode", ClientTarget::OpenCode),
            ("copilot", ClientTarget::Copilot),
        ] {
            assert_eq!(ClientTarget::from_str(s).unwrap(), t);
            assert_eq!(t.to_string(), s);
        }
        assert!(ClientTarget::from_str("vscode").is_err());
        assert_eq!(ClientTarget::default(), ClientTarget::Claude);
    }

    #[test]
    fn path_for_matches_each_client_layout() {
        let w = Path::new("/w");
        assert_eq!(
            ClientTarget::Claude.path_for(w, ArtifactKind::Skill, "code-review"),
            PathBuf::from("/w/.claude/skills/code-review")
        );
        assert_eq!(
            ClientTarget::Claude.path_for(w, ArtifactKind::Rule, "rust-style"),
            PathBuf::from("/w/.claude/rules/rust-style.md")
        );
        assert_eq!(
            ClientTarget::OpenCode.path_for(w, ArtifactKind::Skill, "x"),
            PathBuf::from("/w/.opencode/skills/x")
        );
        assert_eq!(
            ClientTarget::OpenCode.path_for(w, ArtifactKind::Rule, "x"),
            PathBuf::from("/w/.opencode/rules/x.md")
        );
        assert_eq!(
            ClientTarget::Copilot.path_for(w, ArtifactKind::Skill, "x"),
            PathBuf::from("/w/.github/skills/x")
        );
        assert_eq!(
            ClientTarget::Copilot.path_for(w, ArtifactKind::Rule, "rust-style"),
            PathBuf::from("/w/.github/instructions/rust-style.instructions.md")
        );
    }

    #[test]
    fn copilot_transform_strips_frontmatter_and_adds_provenance() {
        let doc = "---\npaths:\n  - \"**/*.rs\"\n---\n# Rust Style\n\nUse 4 spaces.\n";
        let out = copilot_instructions(doc, "ghcr.io/acme/rust-style@sha256:abc", Path::new("rust-style.md")).unwrap();
        let expected = "<!-- generated by grim from ghcr.io/acme/rust-style@sha256:abc; edits will be overwritten -->\n# Rust Style\n\nUse 4 spaces.\n";
        assert_eq!(out, expected);
        assert!(!out.contains("paths:"), "frontmatter must be stripped");
    }

    #[test]
    fn copilot_transform_is_idempotent() {
        let doc = "---\npaths: [\"a\"]\n---\nbody line\n";
        let a = copilot_instructions(doc, "r@sha256:d", Path::new("r.md")).unwrap();
        let b = copilot_instructions(doc, "r@sha256:d", Path::new("r.md")).unwrap();
        assert_eq!(a, b, "regeneration must be byte-identical");
    }

    #[test]
    fn copilot_transform_handles_bare_markdown_rule() {
        let doc = "# Just A Rule\nguidance\n";
        let out = copilot_instructions(doc, "r@sha256:d", Path::new("r.md")).unwrap();
        assert_eq!(
            out,
            "<!-- generated by grim from r@sha256:d; edits will be overwritten -->\n# Just A Rule\nguidance\n"
        );
    }

    #[test]
    fn materialize_rule_claude_is_verbatim() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\n").unwrap();
        let dest = tmp.path().join(".claude/rules/rust-style.md");
        let files = ClientTarget::Claude
            .materialize(ArtifactKind::Rule, "rust-style", &src, &dest, "p")
            .unwrap();
        assert_eq!(files.len(), 1);
        assert!(!files[0].generated);
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# R\n"
        );
    }

    #[test]
    fn materialize_rule_copilot_is_generated_transform() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\nbody\n").unwrap();
        let dest = tmp.path().join(".github/instructions/rust-style.instructions.md");
        let files = ClientTarget::Copilot
            .materialize(ArtifactKind::Rule, "rust-style", &src, &dest, "pin")
            .unwrap();
        assert!(files[0].generated);
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.starts_with("<!-- generated by grim from pin;"));
        assert!(!body.contains("paths:"));
    }

    #[test]
    fn materialize_skill_copies_tree_verbatim_all_clients() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("code-review");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        std::fs::write(root.join("SKILL.md"), "---\nname: code-review\ndescription: d\n---\n").unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        for client in [ClientTarget::Claude, ClientTarget::OpenCode, ClientTarget::Copilot] {
            let dest = tmp.path().join(format!("out-{client}/code-review"));
            let files = client
                .materialize(ArtifactKind::Skill, "code-review", &root, &dest, "p")
                .unwrap();
            assert_eq!(files.len(), 2);
            assert!(files.iter().all(|f| !f.generated));
            assert_eq!(
                std::fs::read_to_string(dest.join("SKILL.md")).unwrap(),
                "---\nname: code-review\ndescription: d\n---\n"
            );
            assert_eq!(
                std::fs::read_to_string(dest.join("scripts/run.sh")).unwrap(),
                "echo hi\n"
            );
        }
    }
}
