// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Grimoire Authors

//! The client-transform seam: turn a materialized canonical artifact tree
//! into the on-disk layout one client expects.
//!
//! **Skills**: every client copies the tree verbatim, except `SKILL.md`
//! when it carries tool-namespaced metadata (`claude.<field>: "…"`): then
//! the index is projected per client via [`super::render`] — Claude gets
//! the native typed fields lifted to the top level; OpenCode/Copilot get
//! a clean universal frontmatter with the tool keys removed.
//!
//! **Rules**: Claude copies the index verbatim (`paths:` is native).
//! OpenCode rewrites it to provenance + body — OpenCode has no per-file
//! path scoping; the file is loaded via the managed `instructions` entry
//! in `opencode.json` (see `opencode_config`). Copilot rewrites it to a
//! `<name>.instructions.md` whose frontmatter maps `paths` → `applyTo`
//! (comma-joined) and `copilot.exclude-agent` → `excludeAgent`.
//!
//! Every transform is deterministic — regenerating the same artifact at
//! the same pinned identifier yields byte-identical output, so a user
//! edit to a generated file is detected as drift exactly like a canonical
//! file (the installer hashes the *expected* generated bytes, not the
//! input).

use std::path::{Path, PathBuf};

use crate::oci::ArtifactKind;
use crate::skill::{AgentFrontmatter, RuleFrontmatter};

use super::install_error::{InstallError, InstallErrorKind};

use super::vendor::Vendor;
use super::vendor_claude::ClaudeVendor;
use super::vendor_codex::CodexVendor;
use super::vendor_copilot::CopilotVendor;
use super::vendor_opencode::OpenCodeVendor;

/// A supported client target.
///
/// Closed internal enum (the binary is the only consumer); `Default` is
/// [`ClientTarget::Claude`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ClientTarget {
    /// Claude Code — `.claude/{skills,rules}`.
    #[default]
    Claude,
    /// OpenCode — `.opencode/{skills,rules}`.
    OpenCode,
    /// GitHub Copilot — `.github/{skills,instructions}` (rules transformed).
    Copilot,
    /// OpenAI Codex — `.agents/skills` + `.codex/agents/<name>.toml`
    /// (skills + agents only; rules unsupported).
    Codex,
}

impl std::str::FromStr for ClientTarget {
    type Err = InstallError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "claude" => Ok(Self::Claude),
            "opencode" => Ok(Self::OpenCode),
            "copilot" => Ok(Self::Copilot),
            "codex" => Ok(Self::Codex),
            other => Err(InstallError::without_reference(InstallErrorKind::UnsupportedClient(
                other.to_string(),
            ))),
        }
    }
}

impl std::fmt::Display for ClientTarget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.vendor().name())
    }
}

/// One file produced for an client target.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MaterializedFile {
    /// The absolute on-disk path written.
    pub path: PathBuf,
    /// Whether the file is a generated transform (vs. a canonical copy).
    /// Generated files are integrity-hashed against their *expected*
    /// bytes so a user edit is still detected as drift.
    pub generated: bool,
}

impl ClientTarget {
    /// Every supported client, in canonical order.
    pub const ALL: [ClientTarget; 4] = [Self::Claude, Self::OpenCode, Self::Copilot, Self::Codex];

    /// The per-vendor materialization strategy behind this identity.
    pub fn vendor(self) -> &'static dyn Vendor {
        match self {
            Self::Claude => &ClaudeVendor,
            Self::OpenCode => &OpenCodeVendor,
            Self::Copilot => &CopilotVendor,
            Self::Codex => &CodexVendor,
        }
    }

    /// The absolute install path for the named artifact of `kind` under
    /// `workspace` at `scope`. A skill installs as a directory; a rule as
    /// a single file. Project scope lands under `<workspace>/<root_dir>`;
    /// global scope lands in the vendor's native user-level discovery
    /// location (see [`Vendor::skills_root`] / [`Vendor::rule_path`]).
    pub fn path_for(
        self,
        workspace: &Path,
        scope: crate::config::scope::ConfigScope,
        kind: ArtifactKind,
        name: &str,
    ) -> PathBuf {
        match kind {
            ArtifactKind::Skill => self.vendor().skills_root(workspace, scope).join(name),
            ArtifactKind::Rule => self.vendor().rule_path(workspace, scope, name),
            ArtifactKind::Agent => self.vendor().agent_path(workspace, scope, name),
            // Bundles never materialize; they expand into members.
            ArtifactKind::Bundle => unreachable!("bundles are never materialized; they expand into members"),
        }
    }

    /// Materialize the canonical artifact tree at `artifact_root` into the
    /// client layout at `dest`.
    ///
    /// `artifact_root` is the extracted canonical content: the skill
    /// directory (`<name>/…`) or the rule index file (`<name>.md`). `dest`
    /// is the final path from [`Self::path_for`]. For a skill, the tree is
    /// copied verbatim. For a rule, Claude/OpenCode copy the index verbatim;
    /// Copilot transforms it (strip `paths:`, prepend provenance header).
    ///
    /// `support_dir` is the optional sibling support directory of a
    /// multi-file rule (`<root>/<name>/`). When present it is copied
    /// verbatim — for every client, including Copilot — beside the index at
    /// `<dest_parent>/<name>/`, so the index's relative links resolve. Only
    /// the index is ever transformed.
    ///
    /// # Errors
    ///
    /// [`InstallErrorKind::TargetIo`] for a filesystem failure;
    /// [`InstallErrorKind::MaterializeFailed`] for an unreadable rule.
    pub fn materialize(
        self,
        kind: ArtifactKind,
        name: &str,
        artifact_root: &Path,
        dest: &Path,
        pinned: &str,
        support_dir: Option<&Path>,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        match kind {
            ArtifactKind::Skill => self.materialize_skill(artifact_root, dest),
            ArtifactKind::Rule => self.materialize_rule(name, artifact_root, dest, pinned, support_dir),
            ArtifactKind::Agent => self.materialize_agent(artifact_root, dest, pinned),
            // Bundles never materialize; they expand into members.
            ArtifactKind::Bundle => unreachable!("bundles are never materialized; they expand into members"),
        }
    }

    /// Copy a skill tree into `dest`. Every file copies verbatim except
    /// `SKILL.md` when it carries tool-namespaced metadata: that index is
    /// rendered per client (and marked `generated`, so the integrity hash
    /// anchors on the *expected rendered* bytes). A plain skill — or a
    /// `SKILL.md` that does not parse — installs byte-identical to the
    /// canonical tree, preserving the historical verbatim contract.
    fn materialize_skill(self, artifact_root: &Path, dest: &Path) -> Result<Vec<MaterializedFile>, InstallError> {
        let mut out = Vec::new();
        copy_tree(artifact_root, dest, &mut out)?;

        let index_src = artifact_root.join("SKILL.md");
        if index_src.is_file() {
            let doc_bytes = std::fs::read(&index_src).map_err(|e| target_io(&index_src, e))?;
            let doc = String::from_utf8_lossy(&doc_bytes);
            let rendered = self
                .vendor()
                .skill_index(&doc)
                .map_err(|e| materialize_failed(e.to_string()))?;
            if let Some(rendered) = rendered {
                for warning in &rendered.warnings {
                    tracing::warn!("{warning}");
                }
                let index_dest = dest.join("SKILL.md");
                std::fs::write(&index_dest, rendered.document.as_bytes()).map_err(|e| target_io(&index_dest, e))?;
                for file in &mut out {
                    if file.path == index_dest {
                        file.generated = true;
                    }
                }
            }
        }

        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }

    /// Materialize a rule: the index goes through the vendor's
    /// [`Vendor::rule_index`] transform (`None` ⇒ verbatim copy); an
    /// optional support directory is copied verbatim beside the index for
    /// every client.
    fn materialize_rule(
        self,
        name: &str,
        artifact_root: &Path,
        dest: &Path,
        pinned: &str,
        support_dir: Option<&Path>,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let bytes = std::fs::read(artifact_root).map_err(|e| target_io(artifact_root, e))?;
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }

        let doc = String::from_utf8_lossy(&bytes);
        let parsed = RuleFrontmatter::parse_doc(&doc, artifact_root).map_err(|e| materialize_failed(e.to_string()))?;
        let rendered = self
            .vendor()
            .rule_index(&parsed, pinned)
            .map_err(|e| materialize_failed(e.to_string()))?;

        let mut out = match rendered {
            // Canonical bytes are what this vendor reads — verbatim copy.
            None => {
                std::fs::write(dest, &bytes).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: false,
                }]
            }
            Some(rendered) => {
                for warning in &rendered.warnings {
                    tracing::warn!("{warning}");
                }
                std::fs::write(dest, rendered.document.as_bytes()).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: true,
                }]
            }
        };

        // Copy the sibling support tree verbatim (all clients, no transform)
        // beside the index at `<dest_parent>/<name>/`, so the index's
        // relative links resolve.
        if let Some(src) = support_dir
            && let Some(parent) = dest.parent()
        {
            copy_tree(src, &parent.join(name), &mut out)?;
        }

        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }

    /// Materialize an agent: the single file goes through the vendor's
    /// [`Vendor::agent_index`] transform (`None` ⇒ verbatim copy). Agents
    /// have no support directory. An unparseable agent document is a
    /// materialize failure — unlike a rule, the frontmatter is required.
    fn materialize_agent(
        self,
        artifact_root: &Path,
        dest: &Path,
        pinned: &str,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let bytes = std::fs::read(artifact_root).map_err(|e| target_io(artifact_root, e))?;
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }

        let doc = String::from_utf8_lossy(&bytes);
        let parsed = AgentFrontmatter::parse_doc(&doc, artifact_root).map_err(|e| materialize_failed(e.to_string()))?;
        let rendered = self
            .vendor()
            .agent_index(&parsed, pinned)
            .map_err(|e| materialize_failed(e.to_string()))?;

        let out = match rendered {
            // Canonical bytes are what this vendor reads — verbatim copy.
            None => {
                std::fs::write(dest, &bytes).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: false,
                }]
            }
            Some(rendered) => {
                for warning in &rendered.warnings {
                    tracing::warn!("{warning}");
                }
                std::fs::write(dest, rendered.document.as_bytes()).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: true,
                }]
            }
        };
        Ok(out)
    }
}

fn materialize_failed(msg: String) -> InstallError {
    InstallError::without_reference(InstallErrorKind::MaterializeFailed(msg))
}

/// Recursively copy every regular file under `src` into `dst`, preserving
/// the relative structure. Records each written file as a canonical
/// (non-generated) [`MaterializedFile`].
fn copy_tree(src: &Path, dst: &Path, out: &mut Vec<MaterializedFile>) -> Result<(), InstallError> {
    let meta = std::fs::symlink_metadata(src).map_err(|e| target_io(src, e))?;
    if meta.is_dir() {
        std::fs::create_dir_all(dst).map_err(|e| target_io(dst, e))?;
        let mut children: Vec<PathBuf> = std::fs::read_dir(src)
            .map_err(|e| target_io(src, e))?
            .map(|e| e.map(|e| e.path()))
            .collect::<std::io::Result<Vec<_>>>()
            .map_err(|e| target_io(src, e))?;
        children.sort();
        for child in children {
            let name = child.file_name().unwrap_or_default();
            copy_tree(&child, &dst.join(name), out)?;
        }
    } else if meta.is_file() {
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }
        std::fs::copy(src, dst).map_err(|e| target_io(dst, e))?;
        out.push(MaterializedFile {
            path: dst.to_path_buf(),
            generated: false,
        });
    }
    Ok(())
}

fn target_io(path: &Path, source: std::io::Error) -> InstallError {
    InstallError::without_reference(InstallErrorKind::TargetIo {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn from_str_and_display_round_trip_lowercase() {
        for (s, t) in [
            ("claude", ClientTarget::Claude),
            ("opencode", ClientTarget::OpenCode),
            ("copilot", ClientTarget::Copilot),
            ("codex", ClientTarget::Codex),
        ] {
            assert_eq!(ClientTarget::from_str(s).unwrap(), t);
            assert_eq!(t.to_string(), s);
        }
        assert!(ClientTarget::from_str("vscode").is_err());
        assert_eq!(ClientTarget::default(), ClientTarget::Claude);
    }

    #[test]
    fn path_for_matches_each_client_layout() {
        let w = Path::new("/w");
        assert_eq!(
            ClientTarget::Claude.path_for(
                w,
                crate::config::scope::ConfigScope::Project,
                ArtifactKind::Skill,
                "code-review"
            ),
            PathBuf::from("/w/.claude/skills/code-review")
        );
        assert_eq!(
            ClientTarget::Claude.path_for(
                w,
                crate::config::scope::ConfigScope::Project,
                ArtifactKind::Rule,
                "rust-style"
            ),
            PathBuf::from("/w/.claude/rules/rust-style.md")
        );
        assert_eq!(
            ClientTarget::OpenCode.path_for(w, crate::config::scope::ConfigScope::Project, ArtifactKind::Skill, "x"),
            PathBuf::from("/w/.opencode/skills/x")
        );
        assert_eq!(
            ClientTarget::OpenCode.path_for(w, crate::config::scope::ConfigScope::Project, ArtifactKind::Rule, "x"),
            PathBuf::from("/w/.opencode/rules/x.md")
        );
        assert_eq!(
            ClientTarget::Copilot.path_for(w, crate::config::scope::ConfigScope::Project, ArtifactKind::Skill, "x"),
            PathBuf::from("/w/.github/skills/x")
        );
        assert_eq!(
            ClientTarget::Copilot.path_for(
                w,
                crate::config::scope::ConfigScope::Project,
                ArtifactKind::Rule,
                "rust-style"
            ),
            PathBuf::from("/w/.github/instructions/rust-style.instructions.md")
        );
        // Codex: skills land in the cross-vendor `.agents/skills` tree;
        // agents are TOML under `.codex/agents`.
        assert_eq!(
            ClientTarget::Codex.path_for(w, crate::config::scope::ConfigScope::Project, ArtifactKind::Skill, "x"),
            PathBuf::from("/w/.agents/skills/x")
        );
        assert_eq!(
            ClientTarget::Codex.path_for(
                w,
                crate::config::scope::ConfigScope::Project,
                ArtifactKind::Agent,
                "rev"
            ),
            PathBuf::from("/w/.codex/agents/rev.toml")
        );
    }

    #[test]
    fn path_for_global_scope_uses_vendor_native_roots() {
        let w = Path::new("/grim-home");
        let g = crate::config::scope::ConfigScope::Global;
        // Native user-level discovery paths (resolvable in any env that
        // has $HOME — the fallback keeps the workspace layout otherwise).
        if let Some(home) = crate::install::vendor::home_dir() {
            assert_eq!(
                ClientTarget::Claude.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".claude/skills/x")
            );
            assert_eq!(
                ClientTarget::Claude.path_for(w, g, ArtifactKind::Rule, "r"),
                home.join(".claude/rules/r.md")
            );
            assert_eq!(
                ClientTarget::Copilot.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".copilot/skills/x")
            );
            // Codex skills follow the cross-vendor `$HOME/.agents/skills`
            // standard — NOT `$CODEX_HOME` (proven by the agent path below).
            assert_eq!(
                ClientTarget::Codex.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".agents/skills/x")
            );
            // Codex agents live under `$CODEX_HOME|~/.codex` + `agents/`; the
            // env-override order is unit-tested in vendor_codex, so only assert
            // the `~/.codex` default when CODEX_HOME is unset.
            if crate::install::vendor::env_dir("CODEX_HOME").is_none() {
                assert_eq!(
                    ClientTarget::Codex.path_for(w, g, ArtifactKind::Agent, "rev"),
                    home.join(".codex/agents/rev.toml")
                );
            }
        }
        if let Some(cfg) = crate::install::vendor::xdg_config_dir() {
            assert_eq!(
                ClientTarget::OpenCode.path_for(w, g, ArtifactKind::Skill, "x"),
                cfg.join("opencode/skills/x")
            );
        }
        // Rules stay in the workspace layout: OpenCode loads them via the
        // absolute instructions glob; Copilot has no global path (warned).
        assert_eq!(
            ClientTarget::OpenCode.path_for(w, g, ArtifactKind::Rule, "r"),
            PathBuf::from("/grim-home/.opencode/rules/r.md")
        );
        assert_eq!(
            ClientTarget::Copilot.path_for(w, g, ArtifactKind::Rule, "r"),
            PathBuf::from("/grim-home/.github/instructions/r.instructions.md")
        );
    }

    #[test]
    fn materialize_rule_claude_is_verbatim() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\n").unwrap();
        let dest = tmp.path().join(".claude/rules/rust-style.md");
        let files = ClientTarget::Claude
            .materialize(ArtifactKind::Rule, "rust-style", &src, &dest, "p", None)
            .unwrap();
        assert_eq!(files.len(), 1);
        assert!(!files[0].generated);
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# R\n"
        );
    }

    #[test]
    fn materialize_rule_copilot_is_generated_transform() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\nbody\n").unwrap();
        let dest = tmp.path().join(".github/instructions/rust-style.instructions.md");
        let files = ClientTarget::Copilot
            .materialize(ArtifactKind::Rule, "rust-style", &src, &dest, "pin", None)
            .unwrap();
        assert!(files[0].generated);
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.starts_with("---\napplyTo: \"a\"\n---\n<!-- generated by grim from pin;"));
        assert!(!body.contains("paths:"));
    }

    #[test]
    fn materialize_rule_opencode_is_generated_body_only() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\nbody\n").unwrap();
        let dest = tmp.path().join(".opencode/rules/rust-style.md");
        let files = ClientTarget::OpenCode
            .materialize(ArtifactKind::Rule, "rust-style", &src, &dest, "pin", None)
            .unwrap();
        assert!(files[0].generated);
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.starts_with("<!-- generated by grim from pin;"));
        assert!(!body.contains("paths:"), "frontmatter stripped for OpenCode");
    }

    #[test]
    fn materialize_rule_claude_with_vendor_metadata_is_generated_cleaned() {
        // Rule symmetry with skills: a rule carrying tool-namespaced
        // metadata is re-rendered for Claude too — foreign vendor keys do
        // not leak into `.claude/rules/`, the file is generated.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(
            &src,
            "---\npaths: [\"**/*.rs\"]\nkeywords: rust\nmetadata:\n  copilot.exclude-agent: code-review\n---\n# R\nbody\n",
        )
        .unwrap();
        let dest = tmp.path().join(".claude/rules/rust-style.md");
        let files = ClientTarget::Claude
            .materialize(ArtifactKind::Rule, "rust-style", &src, &dest, "p", None)
            .unwrap();
        assert!(files[0].generated, "cleaned render is a generated file");
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(!body.contains("copilot.exclude-agent"), "foreign vendor key dropped");
        assert!(body.contains("**/*.rs"), "native paths scoping kept");
        assert!(body.contains("keywords: rust"), "plain catalog key kept");
        assert!(body.ends_with("# R\nbody\n"));
    }

    #[test]
    fn materialize_skill_copies_tree_verbatim_all_clients() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("code-review");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        std::fs::write(root.join("SKILL.md"), "---\nname: code-review\ndescription: d\n---\n").unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        for client in [
            ClientTarget::Claude,
            ClientTarget::OpenCode,
            ClientTarget::Copilot,
            ClientTarget::Codex,
        ] {
            let dest = tmp.path().join(format!("out-{client}/code-review"));
            let files = client
                .materialize(ArtifactKind::Skill, "code-review", &root, &dest, "p", None)
                .unwrap();
            assert_eq!(files.len(), 2);
            assert!(files.iter().all(|f| !f.generated));
            assert_eq!(
                std::fs::read_to_string(dest.join("SKILL.md")).unwrap(),
                "---\nname: code-review\ndescription: d\n---\n"
            );
            assert_eq!(
                std::fs::read_to_string(dest.join("scripts/run.sh")).unwrap(),
                "echo hi\n"
            );
        }
    }

    #[test]
    fn materialize_rule_with_support_dir_claude_verbatim() {
        // The index lands verbatim (paths: is native) and the support tree
        // is copied beside it at `<dest_parent>/<name>/`.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(support.join("nested")).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();
        std::fs::write(support.join("nested/schema.json"), "{}\n").unwrap();

        let dest = tmp.path().join(".claude/rules/my-rule.md");
        let files = ClientTarget::Claude
            .materialize(ArtifactKind::Rule, "my-rule", &src, &dest, "p", Some(support.as_path()))
            .unwrap();

        assert!(files.iter().all(|f| !f.generated), "verbatim copies are not generated");
        let support_dest = dest.parent().unwrap().join("my-rule");
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# index\n"
        );
        assert_eq!(
            std::fs::read_to_string(support_dest.join("examples.md")).unwrap(),
            "# ex\n"
        );
        assert_eq!(
            std::fs::read_to_string(support_dest.join("nested/schema.json")).unwrap(),
            "{}\n"
        );
    }

    #[test]
    fn materialize_rule_with_support_dir_opencode_transforms_index_copies_support() {
        // OpenCode transforms the index (body + provenance); the support
        // dir is copied verbatim beside it so relative links resolve.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(&support).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();

        let dest = tmp.path().join(".opencode/rules/my-rule.md");
        let files = ClientTarget::OpenCode
            .materialize(ArtifactKind::Rule, "my-rule", &src, &dest, "p", Some(support.as_path()))
            .unwrap();

        assert_eq!(files.iter().filter(|f| f.generated).count(), 1);
        let index = std::fs::read_to_string(&dest).unwrap();
        assert!(index.starts_with("<!-- generated by grim from p;"));
        assert!(!index.contains("paths:"));
        assert_eq!(
            std::fs::read_to_string(dest.parent().unwrap().join("my-rule/examples.md")).unwrap(),
            "# ex\n"
        );
    }

    #[test]
    fn materialize_skill_with_namespaced_metadata_renders_per_client() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("next");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        let canonical = "---\nname: next\ndescription: d\nmetadata:\n  keywords: a,b\n  claude.user-invocable: \"false\"\n---\n# body\n";
        std::fs::write(root.join("SKILL.md"), canonical).unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        for client in [
            ClientTarget::Claude,
            ClientTarget::OpenCode,
            ClientTarget::Copilot,
            ClientTarget::Codex,
        ] {
            let dest = tmp.path().join(format!("out-{client}/next"));
            let files = client
                .materialize(ArtifactKind::Skill, "next", &root, &dest, "p", None)
                .unwrap();
            // The rendered index is generated; the sibling stays verbatim.
            let index = dest.join("SKILL.md");
            assert!(
                files.iter().any(|f| f.path == index && f.generated),
                "{client}: SKILL.md must be generated"
            );
            assert!(
                files
                    .iter()
                    .any(|f| f.path == dest.join("scripts/run.sh") && !f.generated),
                "{client}: siblings stay verbatim"
            );
            let doc = std::fs::read_to_string(&index).unwrap();
            assert!(
                !doc.contains("claude.user-invocable"),
                "{client}: namespaced key lifted/dropped"
            );
            assert!(doc.contains("keywords: a,b"), "{client}: plain metadata kept");
            if client == ClientTarget::Claude {
                assert!(doc.contains("user-invocable: false"), "native typed field for Claude");
            } else {
                assert!(!doc.contains("user-invocable"), "{client}: clean universal SKILL.md");
            }
        }
    }

    #[test]
    fn materialize_skill_without_namespaced_metadata_is_byte_identical() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("plain");
        std::fs::create_dir_all(&root).unwrap();
        let canonical = "---\nname: plain\ndescription: d\nmetadata:\n  keywords: a,b\n---\n# body\n";
        std::fs::write(root.join("SKILL.md"), canonical).unwrap();

        for client in [
            ClientTarget::Claude,
            ClientTarget::OpenCode,
            ClientTarget::Copilot,
            ClientTarget::Codex,
        ] {
            let dest = tmp.path().join(format!("out-{client}/plain"));
            let files = client
                .materialize(ArtifactKind::Skill, "plain", &root, &dest, "p", None)
                .unwrap();
            assert!(files.iter().all(|f| !f.generated), "{client}: verbatim fast path");
            assert_eq!(
                std::fs::read_to_string(dest.join("SKILL.md")).unwrap(),
                canonical,
                "{client}: byte-identical install"
            );
        }
    }

    #[test]
    fn materialize_rule_with_support_dir_copilot_transforms_index_copies_support() {
        // Copilot transforms only the index; the support dir is copied
        // verbatim beside it at `.github/instructions/<name>/`.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\nbody\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(&support).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();

        let dest = tmp.path().join(".github/instructions/my-rule.instructions.md");
        let files = ClientTarget::Copilot
            .materialize(
                ArtifactKind::Rule,
                "my-rule",
                &src,
                &dest,
                "pin",
                Some(support.as_path()),
            )
            .unwrap();

        // The index is the single generated file; support files are verbatim.
        assert_eq!(files.iter().filter(|f| f.generated).count(), 1);
        let index = std::fs::read_to_string(&dest).unwrap();
        assert!(index.starts_with("---\napplyTo: \"a\"\n---\n<!-- generated by grim from pin;"));
        assert!(!index.contains("paths:"), "canonical frontmatter mapped, not copied");
        let support_dest = dest.parent().unwrap().join("my-rule");
        assert_eq!(
            std::fs::read_to_string(support_dest.join("examples.md")).unwrap(),
            "# ex\n"
        );
    }
}
