# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The Grimoire Authors
"""Agent artifact kind acceptance tests.

Agents are single ``.md`` files with required frontmatter (``name``,
``description``; optional ``model``, ``tools``, and a ``metadata`` map with
``<vendor>.<field>`` string keys).  Their OCI ``artifactType`` is
``application/vnd.grimoire.agent.v1``.

Build/release:
- ``grim build --kind agent <file>`` / ``grim release --kind agent <file> <ref>``
  (``--kind`` is REQUIRED for agents; a bare ``.md`` defaults to rule).
- A bare ``.md`` whose frontmatter carries both ``name:`` and ``description:``
  (agent-shaped) emits a stderr warning when built/released without ``--kind``.
- name/stem mismatch → exit 65.
- bad vendor literal (e.g. ``metadata.claude.permission-mode``) → exit 65.

Add / config / lock:
- ``grim add <ref>`` infers kind ``agent`` from the manifest
  ``artifactType``; declares the entry in the ``[agents]`` TOML table;
  the lock gets ``[[agent]]`` entries.

Install targets (project scope, all three clients detected):
- **Claude**: ``.claude/agents/<name>.md`` — verbatim byte-identical when
  no ``claude.*`` metadata keys; generated/cleaned render when
  ``claude.*`` keys are present.
- **OpenCode**: ``.opencode/agents/<name>.md`` — ALWAYS generated:
  frontmatter has ``description`` + ``model`` only (NO ``name:``, NO
  ``tools:``); provenance comment ``<!-- generated by grim from … -->``;
  then body.
- **Copilot**: ``.github/agents/<name>.md`` — ALWAYS generated:
  frontmatter ``name``, ``description``, ``tools`` as YAML list
  (comma-split); NO ``model:``; provenance comment; then body.

Override precedence: common ``model: sonnet`` + metadata
``claude.model: opus`` → Claude file has ``model: opus``; OpenCode file
has ``model: sonnet``.

Global scope: honours ``CLAUDE_CONFIG_DIR``, ``COPILOT_HOME``, and
``XDG_CONFIG_HOME`` env overrides.  Copilot agents land natively with NO
inert-rule warning.

Bundles: a bundle source ``.toml`` may carry ``[agents]``; bundle members
with kind ``"agent"`` round-trip through lock → install and are evicted
when the bundle is removed.
"""
from __future__ import annotations

from pathlib import Path

from src.helpers import make_artifact, make_bundle, write_config
from src.registry import REGISTRY_HOST, fetch_manifest
from src.runner import GrimRunner


# ---------------------------------------------------------------------------
# Local helpers
# ---------------------------------------------------------------------------


def _write(p: Path, body: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body)


def _agent_doc(
    name: str = "my-agent",
    model: str = "sonnet",
    tools: str = "Bash,Read",
    extra_metadata: str = "",
) -> str:
    """A canonical agent frontmatter document.

    ``tools`` is a top-level common field (like ``model``); vendor keys go
    into the ``metadata`` map via ``extra_metadata``.
    """
    tools_line = f"tools: {tools}\n" if tools else ""
    meta_block = f"metadata:\n{extra_metadata}" if extra_metadata else ""
    return (
        f"---\n"
        f"name: {name}\n"
        f"description: A test agent.\n"
        f"model: {model}\n"
        f"{tools_line}"
        f"{meta_block}"
        f"---\n"
        f"# {name}\n"
        f"Agent body text.\n"
    )


def _push_agent(
    unique_repo: str,
    name: str = "my-agent",
    model: str = "sonnet",
    tools: str = "Bash,Read",
    extra_metadata: str = "",
    tag: str = "v1",
) -> "src.registry.PublishedArtifact":
    """Push a minimal agent artifact and return the published reference."""
    return make_artifact(
        f"{unique_repo}/{name}",
        "agent",
        {f"{name}.md": _agent_doc(name, model, tools, extra_metadata)},
        tag=tag,
    )


def _detect_all_clients(project_dir: Path) -> None:
    """Create vendor markers so all three clients are detected."""
    (project_dir / ".claude").mkdir(parents=True, exist_ok=True)
    (project_dir / ".opencode").mkdir(parents=True, exist_ok=True)
    (project_dir / ".github" / "instructions").mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# a. release --kind agent publishes with agent artifactType
# ---------------------------------------------------------------------------


def test_release_with_kind_agent_publishes_agent_artifact_type(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``grim release --kind agent`` pushes with
    ``artifactType = application/vnd.grimoire.agent.v1``.

    Uses ``fetch_manifest`` (the same wire-contract verification used in
    ``test_add_infer.py``) and ``grim add`` kind inference to assert the
    OCI manifest carries the correct type.
    """
    agent_file = project_dir / "my-agent.md"
    _write(agent_file, _agent_doc("my-agent"))
    repo_path = f"{unique_repo}/my-agent"
    repo = f"{registry}/{repo_path}"
    runner = grim_at(project_dir)

    out = runner.json("release", "--kind", "agent", str(agent_file), f"{repo}:1.0.0")
    assert out["pushed"] is True

    # Wire-level assertion: manifest carries the agent artifactType.
    manifest = fetch_manifest(repo_path, "1.0.0")
    assert manifest["artifactType"] == "application/vnd.grimoire.agent.v1", (
        f"agent release must set artifactType=application/vnd.grimoire.agent.v1, "
        f"got {manifest.get('artifactType')!r}"
    )
    assert manifest["config"]["mediaType"] == "application/vnd.grimoire.agent.config.v1+json", (
        f"config mediaType must be the agent config type, "
        f"got {manifest['config']['mediaType']!r}"
    )

    # End-to-end: grim add infers kind "agent" from the manifest.
    write_config(project_dir)
    out_add = runner.json("add", f"{repo}:1.0.0")
    assert out_add["kind"] == "agent", (
        f"grim add must infer kind 'agent' from the manifest, got {out_add['kind']!r}"
    )


# ---------------------------------------------------------------------------
# b. bare agent-shaped .md WITHOUT --kind → rule + stderr warning
# ---------------------------------------------------------------------------


def test_bare_agent_shaped_md_without_kind_builds_as_rule_with_warning(
    grim_at, project_dir: Path
) -> None:
    """A ``.md`` with both ``name:`` and ``description:`` (agent-shaped)
    released WITHOUT ``--kind`` is treated as a rule; stderr carries a
    warning that the file "looks like an agent definition".
    """
    agent_file = project_dir / "my-agent.md"
    _write(agent_file, _agent_doc("my-agent"))
    runner = grim_at(project_dir)

    # Use JSON format so we can assert the output kind if the build succeeds.
    result = runner.run("build", str(agent_file), format="json", check=False)
    # The key assertion is the stderr warning.
    assert "looks like an agent" in result.stderr.lower(), (
        f"building an agent-shaped .md without --kind must warn on stderr; "
        f"got stderr: {result.stderr!r}"
    )
    # If it succeeded, the kind in stdout must be "rule", not "agent".
    if result.returncode == 0:
        import json as _json
        out = _json.loads(result.stdout)
        assert out["kind"] == "rule", (
            f"without --kind, an agent-shaped .md must be built as 'rule', "
            f"got {out['kind']!r}"
        )


# ---------------------------------------------------------------------------
# c. add → config [agents] + lock [[agent]]
# ---------------------------------------------------------------------------


def test_add_agent_declares_in_agents_table_and_locks_entry(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``grim add <agent-ref>`` infers kind ``agent`` and writes the
    declaration to the ``[agents]`` TOML table; the lock records an
    ``[[agent]]`` entry pinned by digest.
    """
    ag = _push_agent(unique_repo)
    write_config(project_dir)
    runner = grim_at(project_dir)

    out = runner.json("add", ag.fq)
    assert out["kind"] == "agent", (
        f"add must infer kind 'agent' from manifest, got {out['kind']!r}"
    )
    assert out["name"] == "my-agent"
    assert out["status"] == "added"
    assert "@sha256:" in out["pinned"]

    cfg = (project_dir / "grimoire.toml").read_text()
    assert "[agents]" in cfg, f"config must have [agents] table:\n{cfg}"
    assert "my-agent" in cfg

    lock = (project_dir / "grimoire.lock").read_text()
    assert "my-agent" in lock, f"lock must contain agent entry:\n{lock}"
    assert "@sha256:" in lock


# ---------------------------------------------------------------------------
# d. install (project, all three clients): per-client rendering contract
# ---------------------------------------------------------------------------


def test_install_agent_exits_cleanly_and_lock_has_agent_entry(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``grim install`` succeeds for a project declaring only agents and
    materializes one file per detected client.
    """
    import json as _json

    ag = _push_agent(unique_repo, tools="Bash,Read")
    _detect_all_clients(project_dir)
    write_config(project_dir, agents={"my-agent": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")

    result = runner.run("install", format="json")

    # Lock carries the agent entry.
    lock = (project_dir / "grimoire.lock").read_text()
    assert "my-agent" in lock
    assert "@sha256:" in lock

    rows = _json.loads(result.stdout)
    assert any(r["status"] in ("installed", "unchanged") for r in rows), rows
    claude_file = project_dir / ".claude/agents/my-agent.md"
    assert claude_file.is_file()
    oc_file = project_dir / ".opencode/agents/my-agent.md"
    assert oc_file.is_file() and "name:" not in oc_file.read_text()
    cp_file = project_dir / ".github/agents/my-agent.md"
    assert cp_file.is_file() and "model:" not in cp_file.read_text()


def test_install_agent_per_client_rendering_when_materializer_available(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """Per-client install rendering contract for agents.

    - Claude: ``.claude/agents/<name>.md`` — verbatim (no claude.* keys).
    - OpenCode: ``.opencode/agents/<name>.md`` — no ``name:``/``tools:``;
      has ``description:`` + ``model:``; has provenance comment.
    - Copilot: ``.github/agents/<name>.md`` — has ``name:``, ``description:``,
      ``tools:`` as YAML list; no ``model:``; has provenance comment.
    """
    import json as _json

    ag = _push_agent(unique_repo, tools="Bash,Read")
    _detect_all_clients(project_dir)
    write_config(project_dir, agents={"my-agent": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")

    result = runner.run("install", format="json")
    rows = _json.loads(result.stdout)
    assert any(r["status"] in ("installed", "unchanged") for r in rows), (
        f"install must succeed for at least one client, got: {rows}"
    )

    # Claude: verbatim — all frontmatter fields including name: and tools:.
    claude_file = project_dir / ".claude/agents/my-agent.md"
    assert claude_file.is_file(), (
        "Claude agent file must exist at .claude/agents/my-agent.md"
    )
    claude_text = claude_file.read_text()
    assert "name: my-agent" in claude_text
    assert "description: A test agent." in claude_text
    assert "model: sonnet" in claude_text
    assert "Bash" in claude_text and "Read" in claude_text
    assert "<!-- generated by grim from" not in claude_text, (
        "verbatim Claude agent must not have provenance comment"
    )

    # OpenCode: no name:, no tools:; has description: and model:.
    oc_file = project_dir / ".opencode/agents/my-agent.md"
    assert oc_file.is_file(), (
        "OpenCode agent file must exist at .opencode/agents/my-agent.md"
    )
    oc_text = oc_file.read_text()
    assert "name:" not in oc_text
    assert "tools:" not in oc_text
    assert "description: A test agent." in oc_text
    assert "model: sonnet" in oc_text
    assert "<!-- generated by grim from" in oc_text
    assert "edits will be overwritten" in oc_text

    # Copilot: has name:, description:, tools: as YAML list; no model:.
    cp_file = project_dir / ".github/agents/my-agent.md"
    assert cp_file.is_file(), (
        "Copilot agent file must exist at .github/agents/my-agent.md"
    )
    cp_text = cp_file.read_text()
    assert "name: my-agent" in cp_text
    assert "description: A test agent." in cp_text
    assert "model:" not in cp_text
    assert "Bash" in cp_text
    assert "<!-- generated by grim from" in cp_text


# ---------------------------------------------------------------------------
# e. override precedence: common model + claude.model metadata
# ---------------------------------------------------------------------------


def test_agent_claude_model_metadata_overrides_common_model(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``claude.model: opus`` in agent metadata takes precedence over the
    common ``model: sonnet`` for the Claude client install; OpenCode keeps
    the common ``model: sonnet``.
    """
    # Agent authored with common model=sonnet and claude.model=opus override.
    ag = _push_agent(
        unique_repo,
        name="override-agent",
        model="sonnet",
        extra_metadata='  claude.model: opus\n',
    )
    _detect_all_clients(project_dir)
    write_config(project_dir, agents={"override-agent": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")
    runner.run("install", format="json")

    claude_file = project_dir / ".claude/agents/override-agent.md"
    assert claude_file.is_file()
    claude_text = claude_file.read_text()
    assert "model: opus" in claude_text, (
        f"Claude agent file must use overridden model 'opus':\n{claude_text}"
    )
    assert "model: sonnet" not in claude_text, (
        f"Claude agent file must not contain common model 'sonnet' after override:\n{claude_text}"
    )

    oc_file = project_dir / ".opencode/agents/override-agent.md"
    assert oc_file.is_file()
    oc_text = oc_file.read_text()
    assert "model: sonnet" in oc_text, (
        f"OpenCode agent file must keep common model 'sonnet':\n{oc_text}"
    )
    assert "model: opus" not in oc_text, (
        f"OpenCode agent file must not use Claude-specific 'opus':\n{oc_text}"
    )


# ---------------------------------------------------------------------------
# f. bad claude.permission-mode literal → release exit 65
# ---------------------------------------------------------------------------


def test_release_agent_bad_vendor_literal_exits_65(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``claude.permission-mode: yolo`` is a bad vendor literal for an
    agent; ``grim release --kind agent`` must exit 65.
    """
    bad_doc = (
        "---\n"
        "name: bad-agent\n"
        "description: An agent with bad metadata.\n"
        "model: sonnet\n"
        "metadata:\n"
        "  claude.permission-mode: yolo\n"
        "---\n"
        "# bad-agent\n"
        "Body.\n"
    )
    agent_file = project_dir / "bad-agent.md"
    _write(agent_file, bad_doc)
    repo = f"{registry}/{unique_repo}/bad-agent"
    runner = grim_at(project_dir)

    result = runner.run(
        "release", "--kind", "agent", str(agent_file), f"{repo}:1.0.0",
        check=False,
    )
    assert result.returncode == 65, (
        f"bad vendor literal must exit 65, got {result.returncode}; "
        f"stderr: {result.stderr}"
    )


# ---------------------------------------------------------------------------
# g. status lists agent row with kind "agent"
# ---------------------------------------------------------------------------


def test_status_shows_agent_row_with_kind_agent(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``grim status`` output includes a row for the declared agent with
    ``kind == "agent"``.
    """
    ag = _push_agent(unique_repo)
    write_config(project_dir, agents={"my-agent": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")

    rows = runner.json("status")
    agent_rows = [r for r in rows if r.get("kind") == "agent"]
    assert agent_rows, (
        f"status must include at least one row with kind='agent', got: {rows}"
    )
    ag_row = next(r for r in agent_rows if r["name"] == "my-agent")
    assert ag_row["name"] == "my-agent"


# ---------------------------------------------------------------------------
# h. uninstall deletes files; remove undeclares but leaves files
# ---------------------------------------------------------------------------


def _setup_agent_config(grim_at, project_dir: Path, unique_repo: str):
    """Publish, declare, lock, and install one agent. Returns (runner, ag)."""
    ag = _push_agent(unique_repo, name="del-agent")
    _detect_all_clients(project_dir)
    write_config(project_dir, agents={"del-agent": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")
    runner.run("install")
    return runner, ag


def test_uninstall_agent_undeclares_and_exits_cleanly(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``grim uninstall agent <name>`` must exit 0, report the agent
    as uninstalled, and drop the declaration from the config + lock.
    """
    runner, _ = _setup_agent_config(grim_at, project_dir, unique_repo)

    out = runner.json("uninstall", "agent", "del-agent")
    assert out["kind"] == "agent"
    assert out["name"] == "del-agent"
    assert out["status"] == "uninstalled"

    cfg = (project_dir / "grimoire.toml").read_text()
    assert "del-agent" not in cfg, (
        f"uninstall must remove the agent declaration from config:\n{cfg}"
    )
    lock = project_dir / "grimoire.lock"
    if lock.is_file():
        assert "del-agent" not in lock.read_text(), (
            "uninstall must remove the agent from the lock"
        )

    # status no longer knows the artifact.
    status = runner.json("status")
    assert all(r.get("name") != "del-agent" for r in status)


def test_uninstall_agent_deletes_installed_files_when_present(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """Uninstall removes the installed agent files."""
    ag = _push_agent(unique_repo, name="del-agent2")
    _detect_all_clients(project_dir)
    write_config(project_dir, agents={"del-agent2": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")
    runner.run("install", format="json")

    claude_file = project_dir / ".claude/agents/del-agent2.md"
    assert claude_file.is_file(), "agent must be installed before deletion test"

    runner.json("uninstall", "agent", "del-agent2")
    assert not claude_file.exists(), "uninstall must delete the Claude agent file"


def test_remove_agent_undeclares_but_leaves_installed_files(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """``grim remove agent <name>`` undeclares only; the installed agent
    files remain on disk.
    """
    runner, _ = _setup_agent_config(grim_at, project_dir, unique_repo)

    claude_file = project_dir / ".claude/agents/del-agent.md"
    assert claude_file.is_file(), "agent must be installed before remove test"

    out = runner.json("remove", "agent", "del-agent")
    assert out["status"] == "removed"

    assert claude_file.is_file(), "remove must leave the installed file on disk"

    # Declaration must be gone from config.
    cfg = (project_dir / "grimoire.toml").read_text()
    assert "del-agent" not in cfg, (
        f"remove must undeclare from config:\n{cfg}"
    )


# ---------------------------------------------------------------------------
# i. drift: edit generated OpenCode agent → reinstall refused; --force restores
# ---------------------------------------------------------------------------


def test_drift_edited_opencode_agent_refused_then_force_restores(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """Editing the generated OpenCode agent file after install causes drift.

    A plain ``grim install`` must refuse (exit 65) without overwriting.
    ``--force`` must restore the canonical generated content.
    """
    ag = _push_agent(unique_repo, name="drift-agent")
    _detect_all_clients(project_dir)
    write_config(project_dir, agents={"drift-agent": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")
    runner.run("install", "--client", "opencode", format="json")

    oc_file = project_dir / ".opencode/agents/drift-agent.md"
    assert oc_file.is_file(), "agent must be installed before drift test"

    original_provenance_present = "<!-- generated by grim from" in oc_file.read_text()
    assert original_provenance_present, (
        "OpenCode agent file must have provenance comment before edit"
    )

    # Hand-edit the generated file.
    oc_file.write_text("hand edited by user\n")

    # Without --force: must refuse with exit 65.
    refused = runner.run("install", "--client", "opencode", check=False)
    assert refused.returncode == 65, (
        f"drift on generated OpenCode agent must refuse with 65, "
        f"got {refused.returncode}; {refused.stderr}"
    )
    assert oc_file.read_text() == "hand edited by user\n", (
        "a refused install must not overwrite the user's edit"
    )

    # With --force: must restore the canonical generated content.
    forced = runner.run("install", "--client", "opencode", "--force", check=False)
    assert forced.returncode == 0, forced.stderr
    restored = oc_file.read_text()
    assert "<!-- generated by grim from" in restored, (
        f"forced install must restore the generated agent content:\n{restored}"
    )
    assert "hand edited by user" not in restored, (
        "forced install must overwrite the user's edit"
    )


# ---------------------------------------------------------------------------
# j. name/stem mismatch → release exit 65
# ---------------------------------------------------------------------------


def test_release_agent_name_stem_mismatch_exits_65(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """An agent ``.md`` whose ``name:`` frontmatter differs from its file
    stem must fail with exit 65 at release time.
    """
    # File stem is "wrong-stem" but frontmatter says name: correct-name.
    mismatch_doc = (
        "---\n"
        "name: correct-name\n"
        "description: An agent.\n"
        "model: sonnet\n"
        "---\n"
        "# Agent body.\n"
    )
    agent_file = project_dir / "wrong-stem.md"
    _write(agent_file, mismatch_doc)
    repo = f"{registry}/{unique_repo}/wrong-stem"
    runner = grim_at(project_dir)

    result = runner.run(
        "release", "--kind", "agent", str(agent_file), f"{repo}:1.0.0",
        check=False,
    )
    assert result.returncode == 65, (
        f"name/stem mismatch must exit 65, got {result.returncode}; "
        f"stderr: {result.stderr}"
    )


# ---------------------------------------------------------------------------
# k. global scope install: CLAUDE_CONFIG_DIR, COPILOT_HOME, XDG_CONFIG_HOME
# ---------------------------------------------------------------------------


def test_global_agent_install_exits_cleanly_with_claude_config_dir(
    grim_binary: Path, grim_home: Path, registry: str, unique_repo: str
) -> None:
    """``$CLAUDE_CONFIG_DIR`` is honoured for global scope agent installs."""
    ag = _push_agent(unique_repo, name="global-agent")
    (grim_home / "grimoire.toml").write_text(
        f'[agents]\nglobal-agent = "{ag.fq}"\n'
    )
    runner = GrimRunner(grim_binary, grim_home)
    config_dir = grim_home.parent / "claude-cfg-agent"
    config_dir.mkdir(parents=True, exist_ok=True)
    runner.env["CLAUDE_CONFIG_DIR"] = str(config_dir)
    runner.json("lock", "--global")

    runner.run("install", "--global", "--client", "claude", format="json")

    agent_file = config_dir / "agents/global-agent.md"
    assert agent_file.is_file(), (
        f"global Claude agent must land in $CLAUDE_CONFIG_DIR/agents/; "
        f"got nothing at {agent_file}"
    )
    # Must NOT land in the default ~/.claude tree.
    assert not (runner.home / ".claude/agents/global-agent.md").exists(), (
        "global agent must NOT land in default ~/.claude when CLAUDE_CONFIG_DIR is set"
    )


def test_global_agent_install_exits_cleanly_with_copilot_home_no_inert_warning(
    grim_binary: Path, grim_home: Path, registry: str, unique_repo: str
) -> None:
    """Global Copilot agent install exits 0; unlike global Copilot rules,
    no "will not be discovered" warning appears in stderr.
    """
    ag = _push_agent(unique_repo, name="cp-global-agent")
    (grim_home / "grimoire.toml").write_text(
        f'[agents]\ncp-global-agent = "{ag.fq}"\n'
    )
    runner = GrimRunner(grim_binary, grim_home)
    copilot_home = grim_home.parent / "copilot-home-agent"
    copilot_home.mkdir(parents=True, exist_ok=True)
    runner.env["COPILOT_HOME"] = str(copilot_home)
    runner.json("lock", "--global")

    result = runner.run("install", "--global", "--client", "copilot",
                        format="json")
    # No inert warning in stderr — that warning is rule-only.
    assert "will not be discovered" not in result.stderr.lower(), (
        f"global Copilot agent must not emit the inert-rule warning; "
        f"stderr: {result.stderr!r}"
    )

    agent_file = copilot_home / "agents/cp-global-agent.md"
    assert agent_file.is_file(), (
        f"global Copilot agent must land in $COPILOT_HOME/agents/; "
        f"got nothing at {agent_file}"
    )


def test_global_agent_install_exits_cleanly_with_xdg_config_home(
    grim_binary: Path, grim_home: Path, registry: str, unique_repo: str
) -> None:
    """``$XDG_CONFIG_HOME`` drives the global OpenCode agent install path."""
    ag = _push_agent(unique_repo, name="xdg-agent")
    (grim_home / "grimoire.toml").write_text(
        f'[agents]\nxdg-agent = "{ag.fq}"\n'
    )
    runner = GrimRunner(grim_binary, grim_home)
    xdg = grim_home.parent / "custom-xdg-agent"
    xdg.mkdir(parents=True, exist_ok=True)
    runner.env["XDG_CONFIG_HOME"] = str(xdg)
    runner.json("lock", "--global")

    runner.run("install", "--global", "--client", "opencode", format="json")

    agent_file = xdg / "opencode/agents/xdg-agent.md"
    assert agent_file.is_file(), (
        f"global OpenCode agent must land in $XDG_CONFIG_HOME/opencode/agents/; "
        f"got nothing at {agent_file}"
    )
    assert not (runner.home / ".config/opencode/agents/xdg-agent.md").exists(), (
        "default ~/.config must be untouched when XDG_CONFIG_HOME points elsewhere"
    )


# ---------------------------------------------------------------------------
# l. bundle with an agent member
# ---------------------------------------------------------------------------


def test_bundle_with_agent_member_locks_and_lock_has_provenance(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """A bundle whose members include an agent kind entry is locked; the
    lock carries the agent member with bundle provenance and the member
    installs like a direct declaration.
    """
    ag = _push_agent(unique_repo, name="bundle-agent")
    bundle = make_bundle(
        f"{unique_repo}/mixed-stack",
        [("agent", "bundle-agent", ag.fq)],
        tag="1.0.0",
    )
    _detect_all_clients(project_dir)
    write_config(project_dir, bundles={"mixed-stack": bundle.fq})
    runner = grim_at(project_dir)

    runner.run("lock")

    lock = (project_dir / "grimoire.lock").read_text()
    assert "bundle-agent" in lock, (
        f"bundle agent member must appear in the lock:\n{lock}"
    )
    assert "@sha256:" in lock
    assert f"bundle = \"{REGISTRY_HOST}/{unique_repo}/mixed-stack\"" in lock, (
        f"bundle provenance must be recorded in the lock:\n{lock}"
    )

    runner.run("install", format="json")

    # Verify bundle provenance in status.
    status_rows = runner.json("status")
    agent_row = next(
        (r for r in status_rows if r.get("kind") == "agent" and r["name"] == "bundle-agent"),
        None,
    )
    assert agent_row is not None, (
        f"status must include the bundle agent member row, got: {status_rows}"
    )
    assert "bundle:" in agent_row.get("source", ""), (
        f"bundle agent member must have bundle provenance in status, got: {agent_row}"
    )

    claude_file = project_dir / ".claude/agents/bundle-agent.md"
    assert claude_file.is_file(), (
        "bundle agent member must be installed as a Claude agent file"
    )


def test_remove_bundle_evicts_agent_member_from_lock(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """Removing a bundle that contains an agent member drops the agent
    from the lock (mirrors the existing skill/rule bundle-removal test).
    """
    ag = _push_agent(unique_repo, name="evict-agent")
    bundle = make_bundle(
        f"{unique_repo}/evict-stack",
        [("agent", "evict-agent", ag.fq)],
        tag="1.0.0",
    )
    write_config(project_dir, bundles={"evict-stack": bundle.fq})
    runner = grim_at(project_dir)
    runner.run("lock")
    assert "evict-agent" in (project_dir / "grimoire.lock").read_text()

    out = runner.json("remove", "bundle", "evict-stack")
    assert out["status"] == "removed"

    cfg = (project_dir / "grimoire.toml").read_text()
    assert "evict-stack" not in cfg, "bundle must be undeclared from config"
    lock = (project_dir / "grimoire.lock").read_text()
    assert "evict-agent" not in lock, (
        f"removing the bundle must evict its agent member from the lock:\n{lock}"
    )
